UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5381B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5381B2V-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-AR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-G';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-VEVE';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-VI';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA5566W92T-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA5608UB00-NGR';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA5999S125-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA5999S125-VEAR';
UPDATE products SET collection_name = 'Collezione Fld', collection_code = 'FLD' WHERE sku = 'CA6005FLD-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6024S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-BLU';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6026S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6026S134-N';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6105B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6105B2V-N';
UPDATE products SET collection_name = 'Pql-special2', collection_code = 'PQLS2' WHERE sku = 'CA6172PQLS2-AR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6213W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6216W92-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-AV';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-TM';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-BLU';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-TM';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6289B2V-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6289MOS-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6291C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6291C2OW-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6303MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6303MOS-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA6336W92T-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6383BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6384BR2-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-AR';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-OT';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6455W134-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6456W134-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6465C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6466C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6466C2OW-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6467C2OW-N';