UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-VEVE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA6540UB00-NGR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6564MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6564MOS-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6572W92-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6588B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6588B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6589B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6589B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6590B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6590B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6591B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6591B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6609S135-BE';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6609S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6610S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6615S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6615S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6617S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-G';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-VE';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6620S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6621S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6623S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6627S136-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6631S137-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6632S137-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6633S137-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6638C2OW-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6645MOS-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6646BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6648BR2-BLU';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6677B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6677B2-RO2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6678B2-R';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6686S134-N';