UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY5011B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BY5011MOS-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'BY6021S134-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'BY6021S136-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BY6149BR2-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'BY6380C2OW-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BY6543W92-AZBE2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BY6543W92-VIVI2';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'BY6652S137-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1068B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1068B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1068B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA1068MO-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA1152MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA1152MOS-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA1592W129-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'CA1816AP-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-TM';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA1816BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA1816BR2-VE2';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA1816MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA1816MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA1816MOS-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA1816S134-BLU';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA1816S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA1816S134-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA1816S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA1816S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA1816S136-BLU';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA1816S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA1816S136-VE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-BLGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-NGR';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA1816W129-BLU';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA1816W129-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2174B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2174B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-CU';