UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3111B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3111MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3111MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3111P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-R2';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-TM';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3214MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3214MOS-GR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3214MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3214MOS-VE3';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00-NGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00BML-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3335B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3335B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3335B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3338MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3338MOS-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3339B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3339B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3339B3-VEVE';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3339BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3339BR2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3339MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3339MOS-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3339UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3339UB00-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3347P16-CHEVN';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3444MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3444MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3869P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3869P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4021B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4021B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4021B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA4021MOS-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA4021S135-BE';