UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA4021S135-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA4021W92-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA4021W92T-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4027B3-CU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA4174P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA4174P16-CHEVN';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA4177P16-CHEVN';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4532BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4532BR2-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4532UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4532UB00-NGR';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4536BR2-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4536UB00L-NGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4550UB00BM-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4550UB00BM-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4550UB00BM-NGR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA4576W92-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA4576W92T-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA4577W92-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4762B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4762B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4762B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-TM';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA4818B2V-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA4818B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA4818B2V-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4818BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4818BR2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA4818MOS-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-BLGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-BLU';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-NGR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4827B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4827B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-VE3';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA4828S134-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA5086B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA5086B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA5086MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA5107MOS-N';