UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5246B2R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5255B3-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5585B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5585B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5585B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5585MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5585MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-BLUTM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-VEVE';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5649MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5649MOSR-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'PP5649S137R-BLU';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'PP5649S137R-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'PP5649S137R-VE';
UPDATE products SET collection_name = 'Atlas', collection_code = 'S138' WHERE sku = 'PP5649S138R-AR';
UPDATE products SET collection_name = 'Atlas', collection_code = 'S138' WHERE sku = 'PP5649S138R-G';
UPDATE products SET collection_name = 'Atlas', collection_code = 'S138' WHERE sku = 'PP5649S138R-VE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'PP5649UB00R-NGR';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PP5910W134R-BE';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PP5910W134R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-R3';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-TO';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-VEVE';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-VIVI';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP6340W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP6659B2R-R';