UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-BI2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-G5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-R';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PD1515W134R-BO';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PD1515W134R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-CU';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-CU2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-R3';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'PD1515W92TR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD5216B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD5216B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD5216W92R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6471W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6660B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6660W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6661B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6661B2R-RO2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6661W92R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP1518B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP1518B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP1660MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP2762MOSR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP2762MOSR-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP4822MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP4822MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-N';