UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA2174P16-CHEVN';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA2174S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA2174S134-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA2174S136-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA2174UB00-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2765B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA2765MO-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2849B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2849B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2849B3-TM';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA2849MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA2849MOS-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'CA3084AP-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'CA3084AP-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3084B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3084B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3084B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-R2';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-TM';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3084BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3084BR2-VE2';
UPDATE products SET collection_name = 'Brief 2 Special', collection_code = 'BR2S' WHERE sku = 'CA3084BR2S-GRN';
UPDATE products SET collection_name = 'Brief 2 Special', collection_code = 'BR2S' WHERE sku = 'CA3084BR2S-MCU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3084MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3084MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3084P16-CHEVN';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA3084S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA3084S134-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA3084S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA3084S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA3084S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA3084S136-VE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-BLGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-BLU';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-NGR';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA3084W129-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA3084W129-TM';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA3084W129-VE2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3111B2-MO';