UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP6659W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1240B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1241B2R-MO';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PU1241P16-CHEVBLU';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-CU5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-G9';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PU1243B2VR-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PU1243B2VR-MO';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1243B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1243B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1243B3R-TM';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PU1243P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PU1243P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1392B2R-CU5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1392B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1392B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1392B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1392B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1392B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1392MOSR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1392MOSR-TM';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'PU1392UB00R-BLGR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1393MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1666B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1666B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1666MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1740B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1740B2-MO';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1740B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1740B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1740B3R-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-G9';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-R';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU257MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU257MOSR-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU2634B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU2634B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU2634B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU3891MOSR-TM';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'PU3891UB00R-NGR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU4188B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU4188B2R-VE6';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU4188MOSR-TM';