UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6687S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6690S134BM-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA6692S125-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA6694S125-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6698S135-BE';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6733S135-N';
UPDATE products SET collection_name = 'Cinture Coll.11', collection_code = 'C11' WHERE sku = 'CU3049C11-NB';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CU4209MO-NM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CU4877B3-NBLU2';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CU4877B3-TMN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CU5258B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CU5258B2-MO';
UPDATE products SET collection_name = 'Cinture Coll.81', collection_code = 'C81' WHERE sku = 'CU5270C81-M';
UPDATE products SET collection_name = 'Cinture Coll.81', collection_code = 'C81' WHERE sku = 'CU5270C81-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CU5927MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CU5928MOS-NBLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CU5928MOS-NM';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CU6179W92-R3';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CUBOX15B2R-BLU2';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5284OM5-BLU';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5284OM5-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-BLU';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-R';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-VE';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-BLU';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-BO';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-R';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-VE';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5289OM6-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5289OM6-R';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5289OM6-VE';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM6292OM6-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PA1617B2-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PA4344MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PB2830P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PB2830P16-CHEVN';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'PB5483BR2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1396B2-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1396B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1397B2-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1397B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1397B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3755B2-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3755B2-CU5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3755B2-G9';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3757B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC4216B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1353B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-BI2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-G5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-R';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PD1515W134R-BO';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PD1515W134R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-CU';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-CU2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-R3';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'PD1515W92TR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD5216B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD5216B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD5216W92R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6471W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6660B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6660W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6661B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6661B2R-RO2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6661W92R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP1518B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP1518B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP1660MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP2762MOSR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP2762MOSR-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP4822MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP4822MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-N';