UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5381B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5381B2V-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-AR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-G';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-VEVE';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-VI';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA5566W92T-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA5608UB00-NGR';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA5999S125-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA5999S125-VEAR';
UPDATE products SET collection_name = 'Collezione Fld', collection_code = 'FLD' WHERE sku = 'CA6005FLD-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6024S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-BLU';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6026S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6026S134-N';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6105B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6105B2V-N';
UPDATE products SET collection_name = 'Pql-special2', collection_code = 'PQLS2' WHERE sku = 'CA6172PQLS2-AR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6213W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6216W92-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-AV';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-TM';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-BLU';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-TM';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6289B2V-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6289MOS-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6291C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6291C2OW-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6303MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6303MOS-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA6336W92T-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6383BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6384BR2-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-AR';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-OT';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6455W134-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6456W134-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6465C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6466C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6466C2OW-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6467C2OW-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-VEVE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA6540UB00-NGR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6564MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6564MOS-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6572W92-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6588B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6588B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6589B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6589B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6590B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6590B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6591B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6591B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6609S135-BE';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6609S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6610S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6615S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6615S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6617S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-G';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-VE';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6620S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6621S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6623S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6627S136-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6631S137-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6632S137-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6633S137-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6638C2OW-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6645MOS-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6646BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6648BR2-BLU';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6677B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6677B2-RO2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6678B2-R';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6686S134-N';