UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2141B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2141B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC2141MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC2141MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'AC2141P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2648B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2648B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2648B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'AC2648MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC2648MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC3944B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC3944B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC4221B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC4221B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC4221B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC5099B2-MO';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC5099B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC5099B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC5099B3-TM';
UPDATE products SET collection_name = 'Nessuna Collezione', collection_code = 'NN' WHERE sku = 'AC5565NN-G-M';
UPDATE products SET collection_name = 'Nessuna Collezione', collection_code = 'NN' WHERE sku = 'AC5565NN-N-L';
UPDATE products SET collection_name = 'Nessuna Collezione', collection_code = 'NN' WHERE sku = 'AC5565NN-N-M';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC5592B2-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC5592MOS-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'AC5636APR-TM';
UPDATE products SET collection_name = 'Class-ify', collection_code = 'CY' WHERE sku = 'AC5652CY-GR';
UPDATE products SET collection_name = 'Class-ify', collection_code = 'CY' WHERE sku = 'AC5653CY-GR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC5940B2R-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'AC5940BR2R-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC6156MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC6156MOSR-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'AC6368C2OW-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'AC6369C2OW-N';
UPDATE products SET collection_name = 'Packing Cube', collection_code = 'TA' WHERE sku = 'AC6435TA-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'AC6546S135R-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'AC6706S135-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'AC6708S137-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC6716B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC6717B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC6717B2R-R';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC6732MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AG1142B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BD3336B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BD3336B2-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD3336W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD4870W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD6468W92-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'BD6538W134-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD6656W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD6657W92-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BD6657W92T-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BD6658W92T-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BD6723W92T-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV2960B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV2960B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV2960B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'BV2960MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV2960MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV3849MOS-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4342B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4342B2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV4343BR2-N';
UPDATE products SET collection_name = 'Collezione Pq-light', collection_code = 'POPD' WHERE sku = 'BV4425POPD-N';
UPDATE products SET collection_name = 'Collezione Pq-light', collection_code = 'POPD' WHERE sku = 'BV4425POPD-R';
UPDATE products SET collection_name = 'Pql-special3', collection_code = 'PQLS3' WHERE sku = 'BV4425PQLS3-VE';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV4447BR2-BLU';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'BV4447UB00-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4729B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4729B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4729B2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV4729BR2-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'BV4817UB00BM-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5004B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5004B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5014B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5014B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV5407MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV5993MOS-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV6270BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV6343BR2-N';
UPDATE products SET collection_name = 'Pql-special3', collection_code = 'PQLS3' WHERE sku = 'BV6393PQLS3-VE';
UPDATE products SET collection_name = 'Collezione Pq-light', collection_code = 'PQL' WHERE sku = 'BV6701PQL-R2';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BV6722W92T-BE';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BV6722W92T-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'BV6730C2OW-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BY3058BR2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY3851B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY3851B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY3851B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'BY3851B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'BY3851B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'BY3851B3-TM';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'BY3851MO-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'BY3880UB00-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY5011B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY5011B2-MO';