UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2141B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2141B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC2141B3-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC2141MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC2141MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'AC2141P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2648B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2648B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC2648B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'AC2648MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC2648MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC3944B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC3944B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC4221B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC4221B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC4221B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC5099B2-MO';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC5099B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC5099B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'AC5099B3-TM';
UPDATE products SET collection_name = 'Nessuna Collezione', collection_code = 'NN' WHERE sku = 'AC5565NN-G-M';
UPDATE products SET collection_name = 'Nessuna Collezione', collection_code = 'NN' WHERE sku = 'AC5565NN-N-L';
UPDATE products SET collection_name = 'Nessuna Collezione', collection_code = 'NN' WHERE sku = 'AC5565NN-N-M';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC5592B2-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC5592MOS-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'AC5636APR-TM';
UPDATE products SET collection_name = 'Class-ify', collection_code = 'CY' WHERE sku = 'AC5652CY-GR';
UPDATE products SET collection_name = 'Class-ify', collection_code = 'CY' WHERE sku = 'AC5653CY-GR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC5940B2R-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'AC5940BR2R-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC6156MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC6156MOSR-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'AC6368C2OW-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'AC6369C2OW-N';
UPDATE products SET collection_name = 'Packing Cube', collection_code = 'TA' WHERE sku = 'AC6435TA-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'AC6546S135R-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'AC6706S135-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'AC6708S137-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC6716B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC6717B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AC6717B2R-R';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'AC6732MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'AG1142B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BD3336B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BD3336B2-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD3336W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD4870W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD6468W92-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'BD6538W134-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD6656W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BD6657W92-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BD6657W92T-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BD6658W92T-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BD6723W92T-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV2960B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV2960B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV2960B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'BV2960MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV2960MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV3849MOS-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4342B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4342B2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV4343BR2-N';
UPDATE products SET collection_name = 'Collezione Pq-light', collection_code = 'POPD' WHERE sku = 'BV4425POPD-N';
UPDATE products SET collection_name = 'Collezione Pq-light', collection_code = 'POPD' WHERE sku = 'BV4425POPD-R';
UPDATE products SET collection_name = 'Pql-special3', collection_code = 'PQLS3' WHERE sku = 'BV4425PQLS3-VE';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV4447BR2-BLU';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'BV4447UB00-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4729B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4729B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV4729B2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV4729BR2-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'BV4817UB00BM-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5004B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5004B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5014B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BV5014B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV5407MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BV5993MOS-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV6270BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BV6343BR2-N';
UPDATE products SET collection_name = 'Pql-special3', collection_code = 'PQLS3' WHERE sku = 'BV6393PQLS3-VE';
UPDATE products SET collection_name = 'Collezione Pq-light', collection_code = 'PQL' WHERE sku = 'BV6701PQL-R2';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BV6722W92T-BE';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'BV6722W92T-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'BV6730C2OW-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BY3058BR2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY3851B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY3851B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY3851B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'BY3851B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'BY3851B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'BY3851B3-TM';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'BY3851MO-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'BY3880UB00-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY5011B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY5011B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'BY5011B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'BY5011MOS-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'BY6021S134-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'BY6021S136-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'BY6149BR2-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'BY6380C2OW-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BY6543W92-AZBE2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'BY6543W92-VIVI2';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'BY6652S137-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1068B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1068B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1068B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA1068MO-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA1152MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA1152MOS-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA1592W129-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'CA1816AP-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA1816B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA1816B3-TM';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA1816BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA1816BR2-VE2';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA1816MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA1816MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA1816MOS-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA1816S134-BLU';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA1816S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA1816S134-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA1816S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA1816S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA1816S136-BLU';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA1816S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA1816S136-VE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-BLGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA1816UB00-NGR';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA1816W129-BLU';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA1816W129-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2174B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2174B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2174B3-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA2174P16-CHEVN';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA2174S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA2174S134-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA2174S136-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA2174UB00-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2765B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA2765MO-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA2849B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2849B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2849B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA2849B3-TM';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA2849MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA2849MOS-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'CA3084AP-N';
UPDATE products SET collection_name = 'Harper', collection_code = 'AP' WHERE sku = 'CA3084AP-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3084B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3084B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3084B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-R2';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3084B3-TM';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3084BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3084BR2-VE2';
UPDATE products SET collection_name = 'Brief 2 Special', collection_code = 'BR2S' WHERE sku = 'CA3084BR2S-GRN';
UPDATE products SET collection_name = 'Brief 2 Special', collection_code = 'BR2S' WHERE sku = 'CA3084BR2S-MCU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3084MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3084MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3084P16-CHEVN';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA3084S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA3084S134-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA3084S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA3084S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA3084S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA3084S136-VE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-BLGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-BLU';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3084UB00-NGR';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA3084W129-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA3084W129-TM';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA3084W129-VE2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3111B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3111B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3111MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3111MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3111P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3214B2-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-R2';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3214B3-TM';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3214MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3214MOS-GR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3214MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3214MOS-VE3';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00-NGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3214UB00BML-GRN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3335B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3335B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA3335B2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3338MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3338MOS-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3339B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3339B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA3339B3-VEVE';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3339BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA3339BR2-N';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3339MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3339MOS-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3339UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA3339UB00-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3347P16-CHEVN';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CA3444MO-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA3444MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3869P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA3869P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4021B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4021B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4021B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4021B3-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA4021MOS-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA4021S135-BE';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA4021S135-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA4021W92-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA4021W92T-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4027B3-CU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA4174P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA4174P16-CHEVN';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'CA4177P16-CHEVN';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4532BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4532BR2-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4532UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4532UB00-NGR';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4536BR2-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4536UB00L-NGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4550UB00BM-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4550UB00BM-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4550UB00BM-NGR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA4576W92-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA4576W92T-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA4577W92-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4762B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4762B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4762B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4762B3-TM';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA4818B2V-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA4818B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA4818B2V-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4818BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA4818BR2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA4818MOS-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-BLGR';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-BLU';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-GRN';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA4818UB00-NGR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4827B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA4827B2-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-AR';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA4827B3-VE3';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA4828S134-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA5086B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA5086B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA5086MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA5107MOS-N';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5381B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5381B2V-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-AR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-G';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-VEVE';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA5566W92-VI';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA5566W92T-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA5575B2V-N';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA5608UB00-NGR';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA5999S125-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA5999S125-VEAR';
UPDATE products SET collection_name = 'Collezione Fld', collection_code = 'FLD' WHERE sku = 'CA6005FLD-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6024S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-BLU';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6025S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6026S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6026S134-N';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6105B2V-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6105B2V-N';
UPDATE products SET collection_name = 'Pql-special2', collection_code = 'PQLS2' WHERE sku = 'CA6172PQLS2-AR';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6213W92-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6216W92-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-AV';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6238W129-TM';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-BLU';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-N';
UPDATE products SET collection_name = 'Wollem', collection_code = 'W129' WHERE sku = 'CA6239W129BM-TM';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'CA6289B2V-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6289MOS-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6291C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6291C2OW-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6303MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6303MOS-N';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'CA6336W92T-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6383BR2-N';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6384BR2-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-AR';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6454W134-OT';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6455W134-N';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'CA6456W134-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6465C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6466C2OW-BLU';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6466C2OW-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6467C2OW-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6501B3-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CA6503B3-VEVE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'CA6540UB00-NGR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6564MOS-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6564MOS-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CA6572W92-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6588B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6588B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6589B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6589B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6590B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6590B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6591B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6591B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6592B2BM-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6593B2-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6609S135-BE';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6609S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6610S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6615S135-BLU';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6615S135-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6617S135-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-G';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6619S136-VE';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6620S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6621S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6623S136-N';
UPDATE products SET collection_name = 'Orion', collection_code = 'S136' WHERE sku = 'CA6627S136-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6631S137-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6632S137-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'CA6633S137-N';
UPDATE products SET collection_name = 'Corner Spciale Gommato', collection_code = 'C2OW' WHERE sku = 'CA6638C2OW-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CA6645MOS-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6646BR2-BLU';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'CA6648BR2-BLU';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6677B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6677B2-RO2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CA6678B2-R';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6686S134-N';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6687S134-M';
UPDATE products SET collection_name = 'Cronus', collection_code = 'S134' WHERE sku = 'CA6690S134BM-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA6692S125-N';
UPDATE products SET collection_name = 'Arne', collection_code = 'S125' WHERE sku = 'CA6694S125-N';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6698S135-BE';
UPDATE products SET collection_name = 'Than', collection_code = 'S135' WHERE sku = 'CA6733S135-N';
UPDATE products SET collection_name = 'Cinture Coll.11', collection_code = 'C11' WHERE sku = 'CU3049C11-NB';
UPDATE products SET collection_name = 'Modus', collection_code = 'MO' WHERE sku = 'CU4209MO-NM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CU4877B3-NBLU2';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'CU4877B3-TMN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CU5258B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CU5258B2-MO';
UPDATE products SET collection_name = 'Cinture Coll.81', collection_code = 'C81' WHERE sku = 'CU5270C81-M';
UPDATE products SET collection_name = 'Cinture Coll.81', collection_code = 'C81' WHERE sku = 'CU5270C81-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CU5927MOS-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CU5928MOS-NBLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'CU5928MOS-NM';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'CU6179W92-R3';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'CUBOX15B2R-BLU2';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5284OM5-BLU';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5284OM5-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-BLU';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-R';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM5' WHERE sku = 'OM5285OM5-VE';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-BLU';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-BO';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-R';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5288OM6-VE';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5289OM6-N';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5289OM6-R';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM5289OM6-VE';
UPDATE products SET collection_name = 'Umbrella', collection_code = 'OM6' WHERE sku = 'OM6292OM6-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PA1617B2-MO';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PA4344MOS-N';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PB2830P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PB2830P16-CHEVN';
UPDATE products SET collection_name = 'Brief 2', collection_code = 'BR2' WHERE sku = 'PB5483BR2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1396B2-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1396B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1397B2-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1397B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC1397B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3755B2-AR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3755B2-CU5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3755B2-G9';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC3757B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PC4216B2-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1353B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1354B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-BI2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-G5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD1515B2R-R';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PD1515W134R-BO';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PD1515W134R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-CU';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-CU2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD1515W92R-R3';
UPDATE products SET collection_name = 'Lyra', collection_code = 'W92T' WHERE sku = 'PD1515W92TR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD5216B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD5216B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD5216W92R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6471W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6660B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6660W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6661B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PD6661B2R-RO2';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PD6661W92R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP1518B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP1518B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP1660MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP2762B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP2762B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP2762MOSR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP2762MOSR-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4822B2R-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-MO';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PP4822B2VR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP4822MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP4822MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2BLR-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP4825B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-BLU4';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP4825B3R-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5246B2R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5255B3-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5472B2R-R';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-CU4';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-G';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5585B2BLR-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5585B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5585B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5585B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5585MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5585MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP5649B2BLR-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-BLUTM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-TM';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PP5649B3R-VEVE';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5649MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PP5649MOSR-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'PP5649S137R-BLU';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'PP5649S137R-N';
UPDATE products SET collection_name = 'Collezione S137', collection_code = 'S137' WHERE sku = 'PP5649S137R-VE';
UPDATE products SET collection_name = 'Atlas', collection_code = 'S138' WHERE sku = 'PP5649S138R-AR';
UPDATE products SET collection_name = 'Atlas', collection_code = 'S138' WHERE sku = 'PP5649S138R-G';
UPDATE products SET collection_name = 'Atlas', collection_code = 'S138' WHERE sku = 'PP5649S138R-VE';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'PP5649UB00R-NGR';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PP5910W134R-BE';
UPDATE products SET collection_name = 'Collezione W134', collection_code = 'W134' WHERE sku = 'PP5910W134R-N';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-R3';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-TO';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-VEVE';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP5910W92R-VIVI';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP6340W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PP6659B2R-R';
UPDATE products SET collection_name = 'Circle', collection_code = 'W92' WHERE sku = 'PP6659W92R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1240B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1241B2R-MO';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PU1241P16-CHEVBLU';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-CU5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-G9';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1243B2R-R';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PU1243B2VR-BLU';
UPDATE products SET collection_name = 'B2 Revamp', collection_code = 'B2V' WHERE sku = 'PU1243B2VR-MO';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1243B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1243B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1243B3R-TM';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PU1243P16-CHEVBLU';
UPDATE products SET collection_name = 'P16', collection_code = 'P16' WHERE sku = 'PU1243P16-CHEVN';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1392B2R-CU5';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1392B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1392B2R-R';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1392B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1392B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1392B3R-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1392MOSR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1392MOSR-TM';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'PU1392UB00R-BLGR';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1393MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1666B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1666B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU1666MOSR-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1740B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU1740B2-MO';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1740B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1740B3R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU1740B3R-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-G9';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU257B2R-R';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU257MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU257MOSR-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU2634B2-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU2634B2-MO';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU2634B2-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU3891MOSR-TM';
UPDATE products SET collection_name = 'Urban', collection_code = 'UB00' WHERE sku = 'PU3891UB00R-NGR';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU4188B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU4188B2R-VE6';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU4188MOSR-TM';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU4518MOSR-BLU';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU4518MOSR-N';
UPDATE products SET collection_name = 'Modus Restyling', collection_code = 'MOS' WHERE sku = 'PU4518MOSR-TM';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU5957B2R-BLU2';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU5957B2R-N';
UPDATE products SET collection_name = 'Blue Square', collection_code = 'B2' WHERE sku = 'PU5964B2R-N';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU6190B3R-CU';
UPDATE products SET collection_name = 'Black Square', collection_code = 'B3' WHERE sku = 'PU6190B3R-TM';